Handlers
ilexsor/go-rest-api-homework pull request #1
Opened 2024-12-22 09:47 UTC by ilexsor

2024-12-22 20:38 UTC, dirtymew requested changes
Привет Алекс

хорошая работа - API верно описан

по реализации есть что поправить - см PR

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	r.Get("/task/{id}", getTaskById)
можно упростить название getTask

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	r.Delete("/task/{id}", delTaskById)
лучше deleteTask

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if r.Method != http.MethodDelete {
это лишняя проверка - этого не допустит роутер см см 178

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if len(tasks) == 0 || tasks == nil {
а зачем? если мапа пустая то проверка на 159 строке отдаст ошибку

если она nil то это не задача хендлера и явно что-то не так - лучше путь паника будет

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	w.Write(resp)
_ , _ = w.Write(resp)
тут стоит либо явно проигнорировать ошибку или ее логировать

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if r.Method != http.MethodGet {
код с 111-120 строку лушний

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if r.Method != http.MethodPost {
это лишняя проверка

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if _, ok := tasks[task.ID]; ok {
отлично что добавил эту проверку !

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if r.Method != http.MethodGet {
лишнее

2024-12-22 20:38 UTC, dirtymew commented on precode.go
> +	if len(tasks) == 0 || tasks == nil {
лишнее

2024-12-23 20:24 UTC, dirtymew approved these changes
Привет 

по работе зачет

обрати внимание на комментрии

2024-12-23 20:24 UTC, dirtymew commented on precode.go
> +		http.Error(w, err.Error(), http.StatusInternalServerError)
тут уже это делать бесполезно 

можно только залогировать - пользователю уже ошибку не доставить

2024-12-23 20:24 UTC, dirtymew commented on precode.go
> +func Tasks(w http.ResponseWriter, r *http.Request) {
а почему этот метод экспортируемый, а остальные нет?

лучше чтобы все было единообразно

2024-12-24 10:53 UTC, ilexsor commented
Исправил согласно комментария

2024-12-24 10:54 UTC, merged